# Generated by Django 4.1.5 on 2023-01-26 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_subcategory_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories_2', to='menu.subcategory'),
        ),
    ]
