# Generated by Django 4.1.5 on 2023-01-28 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_category_which_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterField(
            model_name='category',
            name='which_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='which_menu_cat', to='menu.menu', verbose_name='In which menu'),
        ),
    ]
